# 📝 Análisis de Funnel y Conversiones
Este notebook presenta un análisis basado en los módulos provistos.

## 📌 Importación de módulos

In [8]:
import sys
sys.path.append('../')  # Desde notebooks/ sube a raíz

import numpy as np
import data.dataset as dt
import source.calculos as calc
import reportes.formateadores as form
from main import generar_informe_completo

## 📊 Datos utilizados

In [3]:
dt.funnel[:20], dt.tipo_usuario[:20], dt.montos[:20]

(array([1, 3, 2, 1, 0, 0, 0, 3, 1, 2, 0, 3, 2, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0]),
 array([  0, 182,   0,   0,   0,   0,   0, 125,   0,   0,   0,  64,   0,
          0,   0,   0,   0,   0,   0,   0]))

## 🔢 Cálculos principales

In [5]:
tasa_global = calc.calculo_conversion_global(dt.funnel)
tasa_nuevos, tasa_recurrentes = calc.calculo_conversion_especifica(dt.funnel, dt.tipo_usuario)
promedio_monto = calc.ticket_promedio_de_compra(dt.montos, dt.funnel)
cantidad_carrito = calc.cantidad_compras_no_concretadas(dt.funnel)

tasa_global, tasa_nuevos, tasa_recurrentes, promedio_monto, cantidad_carrito

(15.299999999999999,
 13.859649122807017,
 17.209302325581397,
 113.69934640522875,
 176)

## 📄 Reporte formateado

In [9]:
generar_informe_completo()

INFORME
----- CALCULOS -----
La tasa de compradores global es de: 15.30%
La tasa de compradores nuevos es de : 13.86%
La tasa de compradores recurrentes es de : 17.21%
El promedio de ticket de compra es: 113.70
La cantidad de visitantes que solo agregaon al carrito pero no compraron: 176


## 📈 Conclusiones 

A primera vista resalta que ya se tiene un publico que son los visitantes recurrentes, los cuales realizan mas compras que los nuevos visitantes.

Eso quiere decir, que ya se tiene un cierto grupo de personas fieles a la tienda, a pesar de la competencia recurren a esta web para seguir realizando las compras de los productos. Lo ideal seria seguir manteniendolos, dandoles beneficios como envios gratis, cupones de descuento o incluso ofreciendoles un servicio vip. En el servicio vip, ademas de lo mencionado antes, se podria agregar despachos o envios mas rapidos, atencion personalizada, garantia extendida, etc.

Otra observacion, aunque la cantidad de visitantes que no concretan la compra sea baja. De todas formas se puede generar un sistema de notificaciones para recordarles que tienen una compra pendiente, o para avisarles que los productos en su carrito bajaron de precio o estan de descuento, asi pueden concretar su compra.